apiVersion: v1
kind: Pod
metadata: 
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db
      image: postgres:9.4
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRES_USER
          value: "postgres"